embargoes.embargoes_ip_range_entity.*:
  type: config_entity
  label: 'IP Range config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    ranges:
      type: sequence
      label: 'Ranges'
      sequence:
        type: mapping
        mapping:
          range:
            type: string
    proxy_url:
      type: string
      label: 'Proxy URL'
    uuid:
      type: string
