embargoes.embargoes_embargo_entity.*:
  type: config_entity
  label: 'Embargo config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    embargo_type:
      type: boolean 
      label: 'Embargo Type'
    expiration_type:
      type: boolean 
      label: 'Expiration Type'
    expiration_date:
      type: string 
      label: 'Expiration Date'
