embargoes.embargoes_embargo_entity.*:
  type: config_entity
  label: 'Embargo config'
  mapping:
    id:
      type: string
      label: 'ID'
    embargo_type:
      type: boolean
      label: 'Embargo Type'
    expiration_type:
      type: boolean
      label: 'Expiration Type'
    expiration_date:
      type: string
      label: 'Expiration Date'
    exempt_ips:
      type: string
      label: 'Exempt IP Ranges'
    exempt_users:
      type: sequence
      label: 'Exempt Users'
      sequence:
        type: mapping
        mapping:
          target_id:
            type: integer
    embargoed_node:
      type: integer
      label: 'Embargoed Node'
