embargoes.embargoes_ip_range_entity.*:
  type: config_entity
  label: 'IP Range config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    range:
      type: string
      label: 'Range'
    proxy_url:
      type: string
      label: 'Proxy URL'
    uuid:
      type: string
